export const PROJECT_COMMENT_SUCCESS = 'PROJECT_COMMENT_SUCCESS';
export const PROJECT_COMMENT_REQUEST = 'PROJECT_COMMENT_REQUEST';
export const PROJECT_COMMENT_FAIL = 'PROJECT_COMMENT_FAIL';
export const PROJECT_UNCOMMENT_SUCCESS = 'PROJECT_UNCOMMENT_SUCCESS';
export const PROJECT_UNCOMMENT_REQUEST = 'PROJECT_UNCOMMENT_REQUEST';
export const PROJECT_UNCOMMENT_FAIL = 'PROJECT_UNCOMMENT_FAIL';